/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:3.1-32.10" *)
module carry_ripple_adder(in_a, in_b, in_cin, out_sum, out_cout);
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:12.20-12.25" *)
  wire [4:0] carry;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:6.28-6.32" *)
  input [3:0] in_a;
  wire [3:0] in_a;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:6.34-6.38" *)
  input [3:0] in_b;
  wire [3:0] in_b;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:7.16-7.22" *)
  input in_cin;
  wire in_cin;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:9.12-9.20" *)
  output out_cout;
  wire out_cout;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:8.24-8.31" *)
  output [3:0] out_sum;
  wire [3:0] out_sum;
  (* module_not_derived = 32'd1 *)
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:21.24-27.14" *)
  full_adder \genblk1[0].inst_fa  (
    .a(in_a[0]),
    .b(in_b[0]),
    .cin(in_cin),
    .cout(carry[1]),
    .sum(out_sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:21.24-27.14" *)
  full_adder \genblk1[1].inst_fa  (
    .a(in_a[1]),
    .b(in_b[1]),
    .cin(carry[1]),
    .cout(carry[2]),
    .sum(out_sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:21.24-27.14" *)
  full_adder \genblk1[2].inst_fa  (
    .a(in_a[2]),
    .b(in_b[2]),
    .cin(carry[2]),
    .cout(carry[3]),
    .sum(out_sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/carry_ripple_adder.v:21.24-27.14" *)
  full_adder \genblk1[3].inst_fa  (
    .a(in_a[3]),
    .b(in_b[3]),
    .cin(carry[3]),
    .cout(out_cout),
    .sum(out_sum[3])
  );
  assign { carry[4], carry[0] } = { out_cout, in_cin };
endmodule

(* src = "../../RTL_verilog/Carry_Ripple_Adder/full_adder.v:5.1-13.10" *)
module full_adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/full_adder.v:6.16-6.17" *)
  input a;
  wire a;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/full_adder.v:6.19-6.20" *)
  input b;
  wire b;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/full_adder.v:6.22-6.25" *)
  input cin;
  wire cin;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/full_adder.v:7.17-7.21" *)
  output cout;
  wire cout;
  (* src = "../../RTL_verilog/Carry_Ripple_Adder/full_adder.v:7.12-7.15" *)
  output sum;
  wire sum;
  INV_X1 _3_ (
    .A(cin),
    .ZN(_0_)
  );
  NAND2_X1 _4_ (
    .A1(b),
    .A2(a),
    .ZN(_1_)
  );
  XNOR2_X1 _5_ (
    .A(b),
    .B(a),
    .ZN(_2_)
  );
  XNOR2_X1 _6_ (
    .A(cin),
    .B(_2_),
    .ZN(sum)
  );
  OAI21_X1 _7_ (
    .A(_1_),
    .B1(_2_),
    .B2(_0_),
    .ZN(cout)
  );
endmodule
